### ISSUE TITLE
Add link to list of tools on apiblueprint.org 

### ISSUE THREAD

**Issue by netmilk** [connexio-labs/grape-apiary#1]
Hey, 

good job! Nice tool! Can I add it to the [API Blueprint page](https://apiblueprint.org/#tooling) to the list of community tooling? Or, if you want, you can do it by yourself by filing a pull-request on API blueprint github pages.

Adam

**Comment by johnallen3d** [comment]
We would love to have our gem added to the tooling. I will submit a PR here shortly, thanks!

**Comment by johnallen3d** [comment]
PR submitted...
